<a href="https://colab.research.google.com/github/mauro9318/python-numpy-pandas/blob/main/Ejercicio_propuesto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Caso práctico de análisis de datos


In [2]:
import numpy as np

# Paso 1: Crear arrays con datos de ventas mensuales
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

print(meses)
print(ventas_A)
print(ventas_B)
print(ventas_C)

['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
[150 200 250 300 220 210 180 190 230 240 280 300]
[180 210 230 250 270 260 240 250 270 290 310 330]
[200 220 240 260 280 300 320 340 360 380 400 420]


In [4]:
#Realizando cálculos de las ventas por mes

ventas_totales_mes = ventas_A + ventas_B + ventas_C
print(ventas_totales_mes)

La suma total del mes de [ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [8]:
#Operaciones básicas con Numpy
#Operaciones estadísticas

#Precio promedio por productos
media_ventas_A = np.mean(ventas_A)
media_ventas_B = np.mean(ventas_B)
media_ventas_C = np.mean(ventas_C)

print("El precio promedio de el producto ventas_A es: ", "{:.2f}".format(media_ventas_A))
print("El precio promedio de el producto ventas_B es: ", "{:.2f}".format(media_ventas_B))
print("El precio promedio de el producto ventas_C es: ", "{:.2f}".format(media_ventas_C))

print("-------------------------------------------------------------------------------------")

suma_ventas_A = np.sum(ventas_A)
suma_ventas_B = np.sum(ventas_B)
suma_ventas_C = np.sum(ventas_C)

print("El total de ventas de el producto ventas_A es: ", "{:.2f}".format(suma_ventas_A))
print("El total de ventas de el producto ventas_B es: ", "{:.2f}".format(suma_ventas_B))
print("El total de ventas de el producto ventas_C es: ", "{:.2f}".format(suma_ventas_C))


El precio promedio de el producto ventas_A es:  229.17
El precio promedio de el producto ventas_B es:  257.50
El precio promedio de el producto ventas_C es:  310.00
-------------------------------------------------------------------------------------
El total de ventas de el producto ventas_A es:  2750.00
El total de ventas de el producto ventas_B es:  3090.00
El total de ventas de el producto ventas_C es:  3720.00
