<a href="https://colab.research.google.com/github/mauro9318/python-numpy-pandas/blob/main/Elementos_unicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

survey_responses = np.array(["bueno", "excelente","malo","bueno","malo",
                             "excelente","bueno","malo"])


print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [3]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
[3 2 3]


In [7]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)

array_x[1:3] = [10,50]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 50  3  4  5  6  7  8  9]
[10 50]


In [8]:
array_x = np.arange(10)
view_y = array_x[[1,3]] #para asegurar la copia de un segmento del array, se usa [[]]
print(array_x)
print(view_y)

array_x[1:3] = [10,50]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 3]
[ 0 10 50  3  4  5  6  7  8  9]
[1 3]
